### ISSUE TITLE
Создание (склейка) конфига для vim

### ISSUE THREAD

**Issue by alexdrupal** [alexdrupal/vimde#7]
Если пользователь ввел все правильно, то делаем следующее

- создаем папку .vimde (с точкой) в домашней директории пользователя - $HOME/.vimde
- создаем папку для проекта - .vimde/project_name, например .vimde/tut.by
- в папке проекта создаём файл config.vimrc - .vimde/project_name/config.vimrc

config.vimrc - это файл с итоговыми настройками vim. Он получается с помощью "склеивания" информации из нескольких файлов.
Я только что залил в репозиторий файлы шаблонов. Для наглядности прикладываю картинку
![vim3](https://cloud.githubusercontent.com/assets/38625/21635555/88e72612-d26f-11e6-9ab5-7feeb44918b2.png)

Итак, у нас есть папка templates. Внутри будут папки для различных языков программирования, но  пока там только PHP.
Тебе нужно будет сделать примерно следующее
```sh
cat $HOME/vimde/templates/project_language/main.vimrc $HOME/vimde/templates/project_language/project_type.vimrc $HOME/vimde/templates/project_language/keys.vimrc > $HOME/.vimde/project_name/config.vimrc
```
project_language, project_name, project type - это твои переменные

**Comment by IlyaKislenka** [comment]
Я так понял, что эти три действия, делаются с расчётом на то, что у пользователя уже имеется папка vimde в домашнем каталоге и в ней есть 3 файла, из которых можно взять данные для склеивания? 
1) А что если у пользователя нету такой папки? Или она в другом месте?)
cat $HOME/vimde/templates/project_language/main.vimrc 
$HOME/vimde/templates/project_language/project_type.vimrc 
$HOME/vimde/templates/project_language/keys.vimrc 
А после, отправляет содержимое предыдущих трех файлов в ту самую папку что нужно создать, в файл конфига ?
> $HOME/.vimde/project_name/config.vimrc

**Comment by IlyaKislenka** [comment]
Кстати, там же пару переменных что через пробел должны были быть указаты, у меня в коде через нижнее подчёркивание. В project_type у меня plain_php, получается что папку нужно будет назвать так(ту откуда будут браться исходные части для конечного конфига). И так же с vim_version там переменная может быть console_vim. Это я к тому, если ты не заметил))

**Comment by alexdrupal** [comment]
Да, предполагается, что пользователь скачивает наш проект в свою домашнюю папку, а это значит, что у него будет vimde.
По поводу переменных - хорошо, я принял к сведению.
